# Regenerates OrchNoteMapperBuildInfo.h with the current build timestamp.
#
# Run from an `add_custom_target(... ALL COMMAND ${CMAKE_COMMAND} -P
# this-file)` with no OUTPUT/DEPENDS tracking, so it reruns on every single
# build invocation (not just every CMake configure, and not only when a
# source file changed) - see feedback memory
# "Build-timestamp label: CMake, not __DATE__/__TIME__": a __DATE__/__TIME__
# macro baked into one .cpp goes stale on an incremental build that never
# recompiles that file, which defeats the entire point of the label (letting
# the user confirm they're looking at the build they just installed - see
# OrchGate's own GenerateOrchGateBuildInfo.cmake, same pattern).
#
# Expects OUTPUT_FILE to be passed in via -D.

if (NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "GenerateOrchNoteMapperBuildInfo.cmake requires -DOUTPUT_FILE=<path>")
endif()

string(TIMESTAMP ORCHNOTEMAPPER_BUILD_TS "%Y-%m-%d %H:%M:%S" UTC)

file(WRITE "${OUTPUT_FILE}"
"#pragma once
// Auto-generated by cmake/GenerateOrchNoteMapperBuildInfo.cmake on every
// build - do not edit, and do not hand-maintain this value elsewhere.
static constexpr const char* orchNoteMapperBuildTimestamp = \"${ORCHNOTEMAPPER_BUILD_TS} UTC\";
")
